import { useState, useRef } from "react";
import { doc, updateDoc, arrayUnion, increment } from "firebase/firestore";
import { db } from "../firebase";
import { useAuth } from "../context/AuthContext";
import { useSub } from "../context/SubContext";
import { callAI, API_URL, AGE_GROUPS, DIET_OPTIONS, CUISINE_OPTIONS, HEALTH_GOALS } from "../config";
import { trackMealPlanGenerated } from "../utils/analytics";
import { AgeGroupSelector, MealCard } from "../components";

const DEFAULT_PREFS = {
  ageGroup: "adults", diet: "Vegetarian", cuisine: "Indian",
  allergies: "", familySize: "4", goal: "Balanced healthy eating",
  calories: "2000", cookTime: "Any", healthConditions: "",
  weightGoal: "maintain", // NEW: lose / maintain / gain
  vegNonVeg: "veg",       // NEW: veg / nonveg / both
};

const PRICE_LEVEL = ["","₹","₹₹","₹₹₹","₹₹₹₹"];

// Weight goal calorie multipliers
const WEIGHT_GOAL_CONFIG = {
  lose:     { label:"🔥 Lose Weight",    desc:"Calorie deficit",   multiplier: 0.85, color:"#ef4444", bg:"#fef2f2" },
  maintain: { label:"⚖️ Maintain Weight", desc:"Balanced calories", multiplier: 1.00, color:"#0891b2", bg:"#e0f2fe" },
  gain:     { label:"💪 Gain Muscle",    desc:"Calorie surplus",   multiplier: 1.15, color:"#059669", bg:"#d1fae5" },
};

export default function MealPlanner({ navigate }) {
  const { user, profile, updateUserProfile } = useAuth();
  const { plan, canGenerate } = useSub();
  const shareCardRef = useRef(null);

  const [prefs, setPrefs]               = useState(DEFAULT_PREFS);
  const [mealPlan, setMealPlan]         = useState(null);
  const [loading, setLoading]           = useState(false);
  const [error, setError]               = useState("");
  const [activeDay, setActiveDay]       = useState("Monday");
  const [showShopping, setShowShopping] = useState(false);
  const [saving, setSaving]             = useState(false);
  const [saved, setSaved]               = useState(false);
  const [showShareCard, setShowShareCard] = useState(false);

  const [restaurants, setRestaurants]   = useState({});
  const [loadingRest, setLoadingRest]   = useState({});
  const [userLocation, setUserLocation] = useState(null);
  const [locationAsked, setLocationAsked] = useState(false);
  const [locationError, setLocationError] = useState("");

  const [recipeModal, setRecipeModal]     = useState(null);
  const [recipeLoading, setRecipeLoading] = useState(false);
  const [recipeCache, setRecipeCache]     = useState({});
  const [swapping, setSwapping]           = useState({});

  const plansUsed = profile?.plansUsed || 0;
  const canGen    = canGenerate(plansUsed);

  function set(key, val) { setPrefs(p => ({ ...p, [key]: val })); }

  // ── Adjusted calories based on weight goal ─────────────────────────────
  function getAdjustedCalories() {
    const base = parseInt(prefs.calories) || 2000;
    const mult = WEIGHT_GOAL_CONFIG[prefs.weightGoal]?.multiplier || 1;
    return Math.round(base * mult);
  }

  // ── WhatsApp Share ─────────────────────────────────────────────────────
  function shareOnWhatsApp(plan) {
    const day1  = plan.days[0];
    const meals = Object.entries(day1.meals)
      .map(([type, meal]) => `  ${type.charAt(0).toUpperCase()+type.slice(1)}: ${meal.name} (${meal.calories} kcal)`)
      .join("\n");
    const message =
      `🥗 *${plan.planName}*\n\nGenerated by Mitabhukta\n\n` +
      `📅 *Day 1 — ${day1.day}*\n${meals}\n\n` +
      `📊 ${plan.nutrition_summary}\n\n` +
      `_Get your personalized Indian meal plan free at mitabhukta.com_ 🍛`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, "_blank");
  }

  // ── Download share card as image ───────────────────────────────────────
  async function downloadShareCard() {
    setShowShareCard(true);
    // Give DOM time to render
    setTimeout(async () => {
      try {
        const { default: html2canvas } = await import("html2canvas");
        const canvas = await html2canvas(shareCardRef.current, {
          backgroundColor: "#052e16",
          scale: 2,
          useCORS: true,
        });
        const link = document.createElement("a");
        link.download = `mitabhukta-meal-plan-${activeDay.toLowerCase()}.png`;
        link.href = canvas.toDataURL("image/png");
        link.click();
      } catch {
        setError("Could not generate image. Try screenshotting instead.");
      }
      setShowShareCard(false);
    }, 500);
  }

  // ── Location ───────────────────────────────────────────────────────────
  function requestLocation() {
    setLocationAsked(true);
    if (!navigator.geolocation) { setLocationError("Geolocation not supported."); return; }
    navigator.geolocation.getCurrentPosition(
      pos => setUserLocation({ lat:pos.coords.latitude, lng:pos.coords.longitude }),
      ()  => setLocationError("Location denied. Enable location to see nearby restaurants.")
    );
  }

  // ── Fetch Restaurants ──────────────────────────────────────────────────
  async function fetchRestaurants(mealType, mealName) {
    const key = `${activeDay}-${mealType}`;
    if (restaurants[key]||loadingRest[key]) return;
    if (!userLocation) { requestLocation(); return; }
    setLoadingRest(l => ({ ...l, [key]:true }));
    try {
      const keyword = encodeURIComponent(mealName||"restaurant");
      const res = await fetch(`${API_URL.replace("/api/meal-plan","")}/api/places?lat=${userLocation.lat}&lng=${userLocation.lng}&keyword=${keyword}`);
      const data = await res.json();
      setRestaurants(r => ({ ...r, [key]:data.restaurants||[] }));
    } catch {
      setRestaurants(r => ({ ...r, [key]:[] }));
    } finally {
      setLoadingRest(l => ({ ...l, [key]:false }));
    }
  }

  // ── Fetch Recipe ───────────────────────────────────────────────────────
  async function fetchRecipe(mealType, meal) {
    const cacheKey = meal.name;
    if (recipeCache[cacheKey]) { setRecipeModal({ ...meal, mealType, recipe:recipeCache[cacheKey] }); return; }
    setRecipeModal({ ...meal, mealType, loading:true });
    setRecipeLoading(true);
    try {
      const prompt = `You are a professional chef. Give a detailed recipe for "${meal.name}".
Respond ONLY with valid JSON (no markdown):
{
  "name": "${meal.name}",
  "servings": 4,
  "prepTime": "10 min",
  "cookTime": "20 min",
  "difficulty": "Easy",
  "ingredients": [{ "amount": "2 cups", "item": "basmati rice" }],
  "steps": ["Step 1: ...", "Step 2: ..."],
  "tips": ["tip1", "tip2"],
  "nutrition": { "calories": 400, "protein": "12g", "carbs": "55g", "fat": "8g" }
}`;
      const result = await callAI(prompt);
      const recipe = JSON.parse(result.replace(/```json|```/g,"").trim());
      setRecipeCache(c => ({ ...c, [cacheKey]:recipe }));
      setRecipeModal({ ...meal, mealType, recipe });
    } catch {
      setRecipeModal({ ...meal, mealType, recipe:null, error:true });
    } finally { setRecipeLoading(false); }
  }

  // ── Meal Swap ──────────────────────────────────────────────────────────
  async function swapMeal(day, mealType) {
    const key = `${day}-${mealType}`;
    setSwapping(s => ({ ...s, [key]:true }));
    try {
      const ag = AGE_GROUPS[prefs.ageGroup];
      const vegFilter = prefs.vegNonVeg === "veg" ? "strictly vegetarian, no meat or fish" :
                        prefs.vegNonVeg === "nonveg" ? "can include chicken, fish, eggs" : "any";
      const prompt = `Generate ONE alternative ${mealType} meal for ${ag.label} (${ag.range}).
Diet: ${prefs.diet}, Food type: ${vegFilter}, Goal: ${prefs.weightGoal}, Cuisine: ${prefs.cuisine}
Allergies: ${prefs.allergies||"None"}, Nutrition focus: ${ag.nutritionFocus}
Respond ONLY with valid JSON: { "name": "...", "calories": 400, "time": "20 min", "difficulty": "Easy", "description": "..." }`;
      const result  = await callAI(prompt);
      const newMeal = JSON.parse(result.replace(/```json|```/g,"").trim());
      setMealPlan(prev => ({
        ...prev,
        days: prev.days.map(d =>
          d.day===day ? { ...d, meals:{ ...d.meals, [mealType]:newMeal } } : d
        ),
      }));
      setRestaurants(r => { const c={...r}; delete c[`${day}-${mealType}`]; return c; });
    } catch { setError("Failed to swap meal. Please try again."); }
    finally { setSwapping(s => ({ ...s, [key]:false })); }
  }

  // ── Build Prompt ───────────────────────────────────────────────────────
  function buildPrompt() {
    const ag           = AGE_GROUPS[prefs.ageGroup];
    const days         = plan.planDays;
    const adjCalories  = getAdjustedCalories();
    const vegFilter    = prefs.vegNonVeg==="veg"    ? "STRICTLY VEGETARIAN — absolutely no meat, chicken, fish or eggs" :
                         prefs.vegNonVeg==="nonveg" ? "NON-VEGETARIAN — can include chicken, fish, eggs, meat" :
                                                      "Mix of veg and non-veg meals";
    const weightGuide  = prefs.weightGoal==="lose"  ? `WEIGHT LOSS plan — calorie deficit, high fiber, lean protein, avoid heavy carbs at dinner` :
                         prefs.weightGoal==="gain"  ? `MUSCLE GAIN plan — calorie surplus, very high protein (${Math.round(adjCalories*0.3/4)}g+), complex carbs` :
                                                      `MAINTENANCE plan — balanced macros, sustainable eating`;

    return `You are an expert Indian nutritionist and chef. Generate a ${days}-day personalized Indian meal plan.

DIET TYPE: ${vegFilter}
WEIGHT GOAL: ${weightGuide}
Target calories: ${adjCalories} kcal/day
Cuisine: ${prefs.cuisine} | Family size: ${prefs.familySize} people
Age group: ${ag.label} (${ag.range}) | Cook time: ${prefs.cookTime}
Allergies/Avoid: ${prefs.allergies||"None"}
${prefs.healthConditions ? `Health conditions: ${prefs.healthConditions} — adjust plan accordingly` : ""}
Nutrition focus: ${ag.nutritionFocus}
${prefs.ageGroup==="kids" ? "No spicy food. Fun colorful meals kids will enjoy." : ""}
${prefs.ageGroup==="seniors" ? "Soft textures, low sodium, easy digestion, anti-inflammatory." : ""}

Use authentic Indian dishes only. Keep meal descriptions to ONE short sentence.

Respond ONLY with valid JSON (no markdown, no backticks):
{
  "planName": "Short descriptive plan name",
  "ageGroup": "${prefs.ageGroup}",
  "weightGoal": "${prefs.weightGoal}",
  "targetCalories": ${adjCalories},
  "days": [
    {
      "day": "Monday",
      "totalCalories": ${adjCalories},
      "meals": {
        "breakfast": { "name": "Poha", "calories": 320, "time": "15 min", "difficulty": "Easy", "description": "One sentence." },
        "lunch":     { "name": "Dal Rice", "calories": 520, "time": "20 min", "difficulty": "Easy", "description": "One sentence." },
        "snack":     { "name": "Roasted Chana", "calories": 150, "time": "5 min", "difficulty": "Easy", "description": "One sentence." },
        "dinner":    { "name": "Palak Paneer + Roti", "calories": 480, "time": "30 min", "difficulty": "Medium", "description": "One sentence." }
      }
    }
  ],
  "shopping_list": {
    "Vegetables": ["item1", "item2"],
    "Dal & Pulses": ["item1"],
    "Grains & Rice": ["item1"],
    "Dairy": ["item1"],
    "Spices & Masalas": ["item1"],
    "Protein": ["item1"]
  },
  "nutrition_summary": "One sentence summary of the plan.",
  "weekly_tips": ["tip1", "tip2", "tip3"]
}`;
  }

  // ── Generate ───────────────────────────────────────────────────────────
  async function generate() {
    if (!canGen) { setError(`You've used all ${plan.plansPerMonth} plans this month. Upgrade to generate more!`); return; }
    setLoading(true); setError(""); setMealPlan(null);
    setShowShopping(false); setSaved(false);
    setRestaurants({}); setRecipeCache({});
    if (!locationAsked) requestLocation();
    try {
      const result = await callAI(buildPrompt());
      const parsed = JSON.parse(result.replace(/```json|```/g,"").trim());
      setMealPlan(parsed);
      setActiveDay(parsed.days[0]?.day||"Monday");
      trackMealPlanGenerated();
      if (user && plan.plansPerMonth < 999) {
        await updateDoc(doc(db,"users",user.uid),{ plansUsed:increment(1) });
        await updateUserProfile({ plansUsed:plansUsed+1 });
      }
    } catch(e) {
      setError("Failed to generate meal plan. Please try again. "+(e.message||""));
    } finally { setLoading(false); }
  }

  async function savePlan() {
    if (!mealPlan||!user) return;
    setSaving(true);
    try {
      await updateDoc(doc(db,"users",user.uid),{
        savedPlans: arrayUnion({
          id: Date.now().toString(),
          name: mealPlan.planName,
          ageGroup: mealPlan.ageGroup,
          weightGoal: mealPlan.weightGoal,
          createdAt: new Date().toISOString(),
          days: mealPlan.days.length,
          summary: mealPlan.nutrition_summary,
          plan: mealPlan,
        }),
      });
      setSaved(true);
    } catch { setError("Failed to save plan."); }
    finally { setSaving(false); }
  }

  const currentDay = mealPlan?.days?.find(d => d.day===activeDay);
  const wg = WEIGHT_GOAL_CONFIG[prefs.weightGoal];

  return (
    <div className="page">

      {/* ── Recipe Modal ──────────────────────────────────────────────── */}
      {recipeModal && (
        <div style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.55)", zIndex:999, display:"flex", alignItems:"center", justifyContent:"center", padding:20 }} onClick={() => setRecipeModal(null)}>
          <div style={{ background:"var(--bg-card)", borderRadius:"var(--radius-lg)", padding:28, maxWidth:560, width:"100%", maxHeight:"85vh", overflowY:"auto" }} onClick={e => e.stopPropagation()}>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:20 }}>
              <h2 style={{ fontFamily:"var(--font-display)", fontSize:20, color:"var(--primary-dark)" }}>{recipeModal.name}</h2>
              <button onClick={() => setRecipeModal(null)} style={{ background:"none", border:"none", fontSize:20, cursor:"pointer", color:"var(--text-3)" }}>✕</button>
            </div>
            {recipeModal.loading ? (
              <div style={{ textAlign:"center", padding:40 }}>
                <div style={{ width:36, height:36, border:"3px solid var(--border)", borderTop:"3px solid var(--primary)", borderRadius:"50%", animation:"spin 0.8s linear infinite", margin:"0 auto 12px" }} />
                <p style={{ color:"var(--text-3)", fontSize:14 }}>Fetching recipe...</p>
              </div>
            ) : recipeModal.error ? (
              <p style={{ color:"var(--red-500)", fontSize:14 }}>Failed to load recipe. Please try again.</p>
            ) : recipeModal.recipe ? (
              <div>
                <div style={{ display:"flex", gap:10, marginBottom:20, flexWrap:"wrap" }}>
                  {[["Prep",recipeModal.recipe.prepTime],["Cook",recipeModal.recipe.cookTime],["Serves",recipeModal.recipe.servings],["Level",recipeModal.recipe.difficulty]].map(([l,v]) => (
                    <div key={l} style={{ background:"var(--primary-pale)", borderRadius:"var(--radius-sm)", padding:"8px 14px", textAlign:"center" }}>
                      <div style={{ fontSize:11, color:"var(--primary)", textTransform:"uppercase", letterSpacing:".5px", fontWeight:600 }}>{l}</div>
                      <div style={{ fontSize:14, fontWeight:600, color:"var(--primary-dark)" }}>{v}</div>
                    </div>
                  ))}
                </div>
                <h3 style={{ fontSize:15, fontWeight:600, color:"var(--primary-dark)", marginBottom:10 }}>Ingredients</h3>
                <ul style={{ paddingLeft:18, marginBottom:20 }}>
                  {recipeModal.recipe.ingredients?.map((ing,i) => (
                    <li key={i} style={{ fontSize:14, color:"var(--text-2)", marginBottom:6 }}><strong>{ing.amount}</strong> {ing.item}</li>
                  ))}
                </ul>
                <h3 style={{ fontSize:15, fontWeight:600, color:"var(--primary-dark)", marginBottom:10 }}>Instructions</h3>
                {recipeModal.recipe.steps?.map((step,i) => (
                  <div key={i} style={{ display:"flex", gap:12, marginBottom:12 }}>
                    <div style={{ width:24, height:24, borderRadius:"50%", background:"var(--primary)", color:"#fff", display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:700, flexShrink:0 }}>{i+1}</div>
                    <p style={{ fontSize:14, color:"var(--text-2)", lineHeight:1.6, margin:0 }}>{step}</p>
                  </div>
                ))}
                {recipeModal.recipe.tips?.length>0 && (
                  <div style={{ background:"var(--amber-50)", border:"1px solid var(--amber-100)", borderRadius:"var(--radius-sm)", padding:14, marginTop:16 }}>
                    <div style={{ fontSize:13, fontWeight:600, color:"#92400e", marginBottom:8 }}>💡 Chef Tips</div>
                    {recipeModal.recipe.tips.map((tip,i) => <p key={i} style={{ fontSize:13, color:"#92400e", marginBottom:4 }}>• {tip}</p>)}
                  </div>
                )}
              </div>
            ) : null}
          </div>
        </div>
      )}

      {/* ── Instagram Share Card (hidden, used for screenshot) ─────────── */}
      {showShareCard && currentDay && (
        <div style={{ position:"fixed", top:-9999, left:-9999, zIndex:-1 }}>
          <div ref={shareCardRef} style={{ width:400, background:"linear-gradient(135deg,#052e16,#14532d)", padding:32, borderRadius:24, fontFamily:"var(--font-body)" }}>
            <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:24 }}>
              <div style={{ width:40, height:40, borderRadius:10, background:"#4ade80", display:"flex", alignItems:"center", justifyContent:"center", fontSize:20 }}>🥗</div>
              <div>
                <div style={{ fontWeight:700, fontSize:18, color:"#fff" }}>Mitabhukta</div>
                <div style={{ fontSize:11, color:"rgba(255,255,255,0.5)" }}>AI Indian Meal Planner</div>
              </div>
            </div>
            <div style={{ fontSize:13, color:"rgba(255,255,255,0.5)", marginBottom:8, textTransform:"uppercase", letterSpacing:".5px" }}>
              {activeDay}'s Meal Plan
            </div>
            <div style={{ fontSize:20, fontWeight:700, color:"#4ade80", marginBottom:20 }}>
              {mealPlan?.planName}
            </div>
            {Object.entries(currentDay.meals).map(([type,meal]) => (
              <div key={type} style={{ background:"rgba(255,255,255,0.08)", borderRadius:12, padding:"12px 16px", marginBottom:10 }}>
                <div style={{ fontSize:11, color:"rgba(255,255,255,0.4)", textTransform:"uppercase", letterSpacing:".5px", marginBottom:4 }}>{type}</div>
                <div style={{ fontSize:15, fontWeight:600, color:"#fff", marginBottom:4 }}>{meal.name}</div>
                <div style={{ fontSize:12, color:"#4ade80" }}>🔥 {meal.calories} kcal · ⏱ {meal.time}</div>
              </div>
            ))}
            <div style={{ marginTop:20, paddingTop:16, borderTop:"1px solid rgba(255,255,255,0.1)", display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <div style={{ fontSize:13, color:"rgba(255,255,255,0.4)" }}>Total: {currentDay.totalCalories} kcal</div>
              <div style={{ fontSize:13, color:"rgba(255,255,255,0.6)", fontWeight:600 }}>mitabhukta.com</div>
            </div>
          </div>
        </div>
      )}

      {/* ── Page Header ───────────────────────────────────────────────── */}
      <div className="page-title anim-fade-up">
        <h1>🍛 Meal Planner</h1>
        <p>Personalized {plan.planDays}-day Indian meal plans powered by Claude AI</p>
      </div>

      {error && <div className="banner banner-error mb-16">{error}<button onClick={() => setError("")} style={{ background:"none", border:"none", cursor:"pointer", fontWeight:700, marginLeft:8 }}>✕</button></div>}
      {locationError && <div className="banner banner-warn mb-16">{locationError}</div>}
      {!canGen && (
        <div className="banner banner-warn mb-16">
          You've used all {plan.plansPerMonth} plans this month.
          <button onClick={() => navigate("subscription")} style={{ marginLeft:8, color:"var(--primary-dark)", fontWeight:700, background:"none", border:"none", cursor:"pointer" }}>Upgrade now →</button>
        </div>
      )}

      {!mealPlan ? (
        <div className="card anim-fade-up-2" style={{ maxWidth:780, margin:"0 auto" }}>
          <h2 style={{ fontFamily:"var(--font-display)", fontSize:22, color:"var(--primary-dark)", marginBottom:24 }}>
            Customize Your Plan
          </h2>

          {/* ── Veg / Non-Veg Toggle — most prominent ─────────────────── */}
          <div className="form-group">
            <label>Food Preference</label>
            <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:10 }}>
              {[
                { id:"veg",    emoji:"🥦", label:"Vegetarian",     desc:"No meat or fish" },
                { id:"nonveg", emoji:"🍗", label:"Non-Vegetarian", desc:"Chicken, fish, eggs" },
                { id:"both",   emoji:"🍱", label:"Both",           desc:"Mix of veg & non-veg" },
              ].map(o => (
                <button key={o.id} type="button" onClick={() => set("vegNonVeg",o.id)}
                  style={{ padding:"14px 10px", border:`2px solid ${prefs.vegNonVeg===o.id?"var(--primary)":"var(--border)"}`, background:prefs.vegNonVeg===o.id?"var(--primary-pale)":"#fff", borderRadius:"var(--radius-md)", cursor:"pointer", textAlign:"center", transition:"var(--transition)", fontFamily:"var(--font-body)" }}>
                  <div style={{ fontSize:28, marginBottom:6 }}>{o.emoji}</div>
                  <div style={{ fontSize:14, fontWeight:700, color:prefs.vegNonVeg===o.id?"var(--primary-dark)":"var(--text-2)" }}>{o.label}</div>
                  <div style={{ fontSize:11, color:"var(--text-4)", marginTop:2 }}>{o.desc}</div>
                </button>
              ))}
            </div>
          </div>

          {/* ── Weight Goal Toggle ─────────────────────────────────────── */}
          <div className="form-group">
            <label>Weight Goal</label>
            <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:10 }}>
              {Object.entries(WEIGHT_GOAL_CONFIG).map(([id,config]) => (
                <button key={id} type="button" onClick={() => set("weightGoal",id)}
                  style={{ padding:"14px 10px", border:`2px solid ${prefs.weightGoal===id?config.color:"var(--border)"}`, background:prefs.weightGoal===id?config.bg:"#fff", borderRadius:"var(--radius-md)", cursor:"pointer", textAlign:"center", transition:"var(--transition)", fontFamily:"var(--font-body)" }}>
                  <div style={{ fontSize:22, marginBottom:6 }}>{config.label.split(" ")[0]}</div>
                  <div style={{ fontSize:13, fontWeight:700, color:prefs.weightGoal===id?config.color:"var(--text-2)" }}>{config.label.split(" ").slice(1).join(" ")}</div>
                  <div style={{ fontSize:11, color:"var(--text-4)", marginTop:2 }}>{config.desc}</div>
                </button>
              ))}
            </div>
          </div>

          {/* ── Age Group ─────────────────────────────────────────────── */}
          <div className="form-group">
            <AgeGroupSelector selected={prefs.ageGroup} onChange={v => set("ageGroup",v)} allowedGroups={plan.ageGroups} />
          </div>

          {/* ── Other preferences ─────────────────────────────────────── */}
          <div className="grid-2">
            <div className="form-group">
              <label>Dietary Preference</label>
              <select className="form-control" value={prefs.diet} onChange={e => set("diet",e.target.value)}>
                {DIET_OPTIONS.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Cuisine Style</label>
              <select className="form-control" value={prefs.cuisine} onChange={e => set("cuisine",e.target.value)}>
                {CUISINE_OPTIONS.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Daily Calories (base)</label>
              <select className="form-control" value={prefs.calories} onChange={e => set("calories",e.target.value)}>
                {["1200","1500","1800","2000","2200","2500","3000"].map(o => <option key={o} value={o}>{o} kcal</option>)}
              </select>
              <p className="form-hint">
                Adjusted target: <strong>{getAdjustedCalories()} kcal</strong> based on your {prefs.weightGoal} goal
              </p>
            </div>
            <div className="form-group">
              <label>Family Size</label>
              <select className="form-control" value={prefs.familySize} onChange={e => set("familySize",e.target.value)}>
                {["1","2","3","4","5","6","7","8"].map(o => <option key={o} value={o}>{o} {o==="1"?"person":"people"}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Cook Time</label>
              <select className="form-control" value={prefs.cookTime} onChange={e => set("cookTime",e.target.value)}>
                {["Any","Under 15 min","Under 30 min","Under 45 min"].map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Health Goal</label>
              <select className="form-control" value={prefs.goal} onChange={e => set("goal",e.target.value)}>
                {HEALTH_GOALS.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
          </div>

          <div className="form-group">
            <label>Allergies / Foods to Avoid</label>
            <input className="form-control" type="text" placeholder="e.g. peanuts, dairy, gluten..."
              value={prefs.allergies} onChange={e => set("allergies",e.target.value)} />
          </div>
          <div className="form-group">
            <label>Health Conditions (optional)</label>
            <input className="form-control" type="text"
              placeholder="e.g. diabetes, high cholesterol, thyroid, PCOD, hypertension..."
              value={prefs.healthConditions} onChange={e => set("healthConditions",e.target.value)} />
          </div>

          {/* Plan summary */}
          <div style={{ background:"var(--primary-pale)", border:"1px solid var(--primary-soft)", borderRadius:"var(--radius-sm)", padding:"14px 16px", marginBottom:20 }}>
            <div style={{ display:"flex", gap:16, flexWrap:"wrap", fontSize:13, color:"var(--primary-dark)" }}>
              <span>📅 <strong>{plan.planDays} days</strong></span>
              <span>🎯 <strong>{getAdjustedCalories()} kcal/day</strong></span>
              <span>{prefs.vegNonVeg==="veg"?"🥦 Veg":prefs.vegNonVeg==="nonveg"?"🍗 Non-veg":"🍱 Mixed"}</span>
              <span>{WEIGHT_GOAL_CONFIG[prefs.weightGoal].label}</span>
              <span>{plan.plansPerMonth>=999?"♾️ Unlimited plans":`${Math.max(0,plan.plansPerMonth-plansUsed)} plans remaining`}</span>
            </div>
          </div>

          <button className="btn btn-primary btn-full btn-lg" onClick={generate} disabled={loading||!canGen}>
            {loading
              ? <><span className="spin">⟳</span>&nbsp; Generating your plan (20–30 sec)...</>
              : `✨ Generate My ${plan.planDays}-Day ${prefs.vegNonVeg==="veg"?"Veg":prefs.vegNonVeg==="nonveg"?"Non-Veg":""} Meal Plan`}
          </button>
        </div>
      ) : (
        <div className="anim-fade-in">
          {/* ── Plan header ──────────────────────────────────────────── */}
          <div className="card" style={{ marginBottom:20 }}>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", flexWrap:"wrap", gap:12 }}>
              <div>
                <h2 style={{ fontFamily:"var(--font-display)", fontSize:22, color:"var(--primary-dark)", marginBottom:6 }}>
                  {mealPlan.planName}
                </h2>
                <p style={{ fontSize:14, color:"var(--text-3)", maxWidth:560 }}>{mealPlan.nutrition_summary}</p>
                <div style={{ display:"flex", gap:8, marginTop:8, flexWrap:"wrap" }}>
                  <span style={{ fontSize:12, background:wg.bg, color:wg.color, padding:"3px 10px", borderRadius:"var(--radius-full)", fontWeight:600 }}>
                    {wg.label}
                  </span>
                  <span style={{ fontSize:12, background:"var(--primary-pale)", color:"var(--primary-dark)", padding:"3px 10px", borderRadius:"var(--radius-full)", fontWeight:600 }}>
                    🎯 {mealPlan.targetCalories||getAdjustedCalories()} kcal/day
                  </span>
                  <span style={{ fontSize:12, background:"#f3f4f6", color:"#374151", padding:"3px 10px", borderRadius:"var(--radius-full)", fontWeight:600 }}>
                    {prefs.vegNonVeg==="veg"?"🥦 Vegetarian":prefs.vegNonVeg==="nonveg"?"🍗 Non-Vegetarian":"🍱 Mixed"}
                  </span>
                </div>
              </div>
              <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>
                {plan.shoppingList && (
                  <button className="btn btn-ghost btn-sm" onClick={() => setShowShopping(s=>!s)}>
                    {showShopping?"📅 View Plan":"🛒 Shopping List"}
                  </button>
                )}
                <button className="btn btn-ghost btn-sm" onClick={() => shareOnWhatsApp(mealPlan)}
                  style={{ color:"#25D366", borderColor:"#25D366" }}>
                  💬 WhatsApp
                </button>
                <button className="btn btn-ghost btn-sm" onClick={downloadShareCard}
                  style={{ color:"#E1306C", borderColor:"#E1306C" }}>
                  📸 Share Card
                </button>
                <button className="btn btn-ghost btn-sm" onClick={savePlan} disabled={saving||saved}>
                  {saved?"✅ Saved!":saving?"Saving...":"💾 Save"}
                </button>
                <button className="btn btn-secondary btn-sm"
                  onClick={() => { setMealPlan(null); setSaved(false); setRestaurants({}); }}>
                  + New Plan
                </button>
              </div>
            </div>
          </div>

          {!showShopping ? (
            <>
              {/* Day tabs */}
              <div style={{ display:"flex", gap:8, marginBottom:20, flexWrap:"wrap" }}>
                {mealPlan.days.map(d => (
                  <button key={d.day} onClick={() => setActiveDay(d.day)}
                    style={{ padding:"8px 18px", borderRadius:"var(--radius-full)", border:"1.5px solid", borderColor:activeDay===d.day?"var(--primary)":"var(--border)", background:activeDay===d.day?"var(--primary)":"#fff", color:activeDay===d.day?"#fff":"var(--text-3)", fontSize:14, fontWeight:500, cursor:"pointer", transition:"var(--transition)" }}>
                    {d.day.slice(0,3)}
                    {d.totalCalories&&<span style={{ fontSize:10, marginLeft:4, opacity:0.7 }}>{d.totalCalories}kcal</span>}
                  </button>
                ))}
              </div>

              {/* Meals grid */}
              {currentDay && (
                <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))", gap:20 }}>
                  {Object.entries(currentDay.meals).map(([type,meal]) => {
                    const restKey      = `${activeDay}-${type}`;
                    const restList     = restaurants[restKey]||[];
                    const isLoadingRest = loadingRest[restKey];
                    const isSwapping   = swapping[`${activeDay}-${type}`];
                    return (
                      <div key={type}>
                        <MealCard type={type} meal={meal} />
                        <div style={{ display:"flex", gap:8, marginTop:8, flexWrap:"wrap" }}>
                          <button className="btn btn-ghost btn-sm" onClick={() => fetchRecipe(type,meal)} style={{ fontSize:12 }}>📖 Recipe</button>
                          <button className="btn btn-ghost btn-sm" onClick={() => swapMeal(activeDay,type)} disabled={isSwapping} style={{ fontSize:12 }}>
                            {isSwapping?<><span className="spin">⟳</span> Swapping...</>:"🔄 Swap"}
                          </button>
                          <button className="btn btn-ghost btn-sm" onClick={() => fetchRestaurants(type,meal.name)} style={{ fontSize:12 }}>📍 Nearby</button>
                        </div>

                        {isLoadingRest && (
                          <div style={{ marginTop:10, padding:12, background:"var(--bg-muted)", borderRadius:"var(--radius-sm)", fontSize:13, color:"var(--text-3)" }}>
                            <span className="spin">⟳</span> Finding nearby restaurants...
                          </div>
                        )}

                        {restList.length>0 && (
                          <div style={{ marginTop:10 }}>
                            <div style={{ fontSize:12, fontWeight:700, textTransform:"uppercase", letterSpacing:".5px", color:"var(--text-3)", marginBottom:8 }}>📍 Nearby</div>
                            {restList.map((r,i) => (
                              <div key={i} style={{ background:"#fff", border:"1px solid var(--border)", borderRadius:"var(--radius-sm)", padding:"10px 12px", marginBottom:8, display:"flex", justifyContent:"space-between", alignItems:"center", gap:8 }}>
                                <div style={{ flex:1, minWidth:0 }}>
                                  <div style={{ fontSize:13, fontWeight:600, color:"var(--text)", marginBottom:2, whiteSpace:"nowrap", overflow:"hidden", textOverflow:"ellipsis" }}>{r.name}</div>
                                  <div style={{ fontSize:11, color:"var(--text-3)" }}>
                                    {r.rating&&<span>⭐ {r.rating}</span>}
                                    {r.openNow!==undefined&&<span style={{ marginLeft:8, color:r.openNow?"var(--primary)":"var(--red-500)" }}>{r.openNow?"Open":"Closed"}</span>}
                                  </div>
                                </div>
                                <div style={{ display:"flex", gap:6, flexShrink:0 }}>
                                  <a href={`https://www.swiggy.com/search?query=${encodeURIComponent(r.name)}`} target="_blank" rel="noopener noreferrer"
                                    style={{ padding:"4px 8px", background:"#fc8019", color:"#fff", borderRadius:4, fontSize:11, fontWeight:600, textDecoration:"none" }}>Swiggy</a>
                                  <a href={`https://www.zomato.com/search?q=${encodeURIComponent(r.name)}`} target="_blank" rel="noopener noreferrer"
                                    style={{ padding:"4px 8px", background:"#e23744", color:"#fff", borderRadius:4, fontSize:11, fontWeight:600, textDecoration:"none" }}>Zomato</a>
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* Weekly tips */}
              {mealPlan.weekly_tips?.length>0 && (
                <div className="card mt-24">
                  <h3 style={{ fontFamily:"var(--font-display)", fontSize:18, color:"var(--primary-dark)", marginBottom:14 }}>💡 Weekly Tips</h3>
                  {mealPlan.weekly_tips.map((tip,i) => (
                    <div key={i} style={{ display:"flex", gap:10, fontSize:14, color:"var(--text-2)", marginBottom:8, lineHeight:1.6 }}>
                      <span style={{ color:"var(--primary)", flexShrink:0 }}>✓</span>{tip}
                    </div>
                  ))}
                </div>
              )}

              {/* Grocery links */}
              <div className="card mt-24" style={{ background:"var(--primary-pale)", border:"1px solid var(--primary-soft)" }}>
                <h3 style={{ fontFamily:"var(--font-display)", fontSize:18, color:"var(--primary-dark)", marginBottom:12 }}>🛒 Order Groceries Online</h3>
                <div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
                  {[
                    { name:"BigBasket", url:"https://www.bigbasket.com", color:"#84c225", emoji:"🧺" },
                    { name:"Blinkit",   url:"https://blinkit.com",       color:"#f8c200", emoji:"⚡" },
                    { name:"Zepto",     url:"https://www.zeptonow.com",  color:"#8025f6", emoji:"🟣" },
                    { name:"JioMart",   url:"https://www.jiomart.com",   color:"#0072bc", emoji:"🔵" },
                  ].map(g => (
                    <a key={g.name} href={g.url} target="_blank" rel="noopener noreferrer"
                      style={{ padding:"10px 18px", background:"#fff", border:`1.5px solid ${g.color}`, borderRadius:"var(--radius-sm)", fontSize:14, fontWeight:600, color:g.color, textDecoration:"none", display:"flex", alignItems:"center", gap:6 }}>
                      {g.emoji} {g.name}
                    </a>
                  ))}
                </div>
              </div>
            </>
          ) : (
            /* Shopping List */
            <div className="card">
              <h3 style={{ fontFamily:"var(--font-display)", fontSize:22, color:"var(--primary-dark)", marginBottom:20 }}>🛒 Shopping List</h3>
              <div className="grid-3">
                {Object.entries(mealPlan.shopping_list).map(([cat,items]) => (
                  <div key={cat}>
                    <div style={{ fontSize:12, fontWeight:700, textTransform:"uppercase", letterSpacing:".8px", color:"var(--primary)", marginBottom:10 }}>{cat}</div>
                    {items.map(item => (
                      <label key={item} style={{ display:"flex", alignItems:"center", gap:8, fontSize:14, color:"var(--text-2)", marginBottom:8, cursor:"pointer" }}>
                        <input type="checkbox" style={{ cursor:"pointer", accentColor:"var(--primary)" }} />
                        {item}
                      </label>
                    ))}
                  </div>
                ))}
              </div>
              <div style={{ marginTop:24, paddingTop:20, borderTop:"1px solid var(--border)" }}>
                <div style={{ fontSize:13, fontWeight:600, color:"var(--text-3)", marginBottom:12 }}>Order online:</div>
                <div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
                  {[
                    { name:"BigBasket", url:"https://www.bigbasket.com", color:"#84c225" },
                    { name:"Blinkit",   url:"https://blinkit.com",       color:"#f8c200" },
                    { name:"Zepto",     url:"https://www.zeptonow.com",  color:"#8025f6" },
                    { name:"JioMart",   url:"https://www.jiomart.com",   color:"#0072bc" },
                  ].map(g => (
                    <a key={g.name} href={g.url} target="_blank" rel="noopener noreferrer"
                      style={{ padding:"8px 16px", background:"#fff", border:`1.5px solid ${g.color}`, borderRadius:"var(--radius-sm)", fontSize:13, fontWeight:600, color:g.color, textDecoration:"none" }}>
                      {g.name} →
                    </a>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}