export default function TermsOfService({ navigate }) {
  return (
    <div className="page-md" style={{ margin: "0 auto", padding: "48px 24px" }}>
      <div className="page-title anim-fade-up">
        <h1>📋 Terms of Service</h1>
        <p>Last updated: April 2026 · Please read carefully before using NourishAI</p>
      </div>

      <div className="card anim-fade-up-2" style={{ marginBottom: 20, background: "var(--primary-pale)", border: "1px solid var(--primary-soft)" }}>
        <p style={{ fontSize: 14, color: "var(--primary-dark)", lineHeight: 1.8 }}>
          These Terms of Service ("Terms") govern your use of NourishAI ("Service"), operated by NourishAI ("we", "us", "our"), based in Bengaluru, Karnataka, India. By using our Service, you agree to these Terms. If you disagree, please do not use the Service.
        </p>
      </div>

      {[
        {
          title: "1. Acceptance of Terms",
          items: [
            { subtitle: "Agreement", text: "By creating an account or using NourishAI, you confirm that you are at least 13 years of age and agree to be bound by these Terms and our Privacy Policy." },
            { subtitle: "Updates", text: "We may update these Terms at any time. We will notify you of significant changes via email or in-app notice. Continued use after changes constitutes acceptance." },
          ],
        },
        {
          title: "2. Use of the Service",
          items: [
            { subtitle: "Permitted use", text: "NourishAI is for personal, non-commercial use. You may use it to plan meals, track nutrition, book trainer sessions, and access wellness features." },
            { subtitle: "Prohibited use", text: "You may not: scrape or copy our AI-generated content for commercial purposes, impersonate other users, attempt to hack or disrupt the service, share your account credentials, or use the platform for any unlawful purpose." },
            { subtitle: "Account responsibility", text: "You are responsible for all activity under your account. Keep your password secure and notify us immediately of any unauthorized access at support@nourishai.com." },
          ],
        },
        {
          title: "3. Subscriptions & Payments",
          items: [
            { subtitle: "Pricing", text: "Subscription prices are displayed in Indian Rupees (₹) and include applicable taxes. Prices may change with 30 days notice." },
            { subtitle: "Billing", text: "Subscriptions are billed monthly via Razorpay. Your subscription auto-renews unless cancelled before the renewal date." },
            { subtitle: "Refunds", text: "We offer a 7-day refund on first-time subscriptions if you are not satisfied. Refunds are processed within 5-7 business days to your original payment method." },
            { subtitle: "Cancellation", text: "You can cancel your subscription anytime from Account Settings. Cancellation takes effect at the end of your current billing period." },
          ],
        },
        {
          title: "4. Trainer Bookings",
          items: [
            { subtitle: "Platform-only transactions", text: "All trainer bookings and payments must be made through NourishAI. Off-platform payments are prohibited and void our service guarantees." },
            { subtitle: "Cancellation policy", text: "Session cancellations 12+ hours before are fully refunded. Cancellations within 12 hours may incur fees as detailed in our booking policy." },
            { subtitle: "Trainer conduct", text: "NourishAI vets all trainers but is not liable for the content of advice given during sessions. Always consult a qualified medical professional before starting any fitness program." },
          ],
        },
        {
          title: "5. AI-Generated Content",
          items: [
            { subtitle: "Not medical advice", text: "Meal plans, calorie estimates, and nutrition information generated by NourishAI are for informational purposes only and do not constitute medical or dietary advice. Always consult a registered dietitian or doctor for medical nutrition therapy." },
            { subtitle: "Accuracy", text: "AI-generated content may not always be accurate. Calorie estimates from photos are approximations. Always verify nutritional information if you have specific medical dietary requirements." },
            { subtitle: "Intellectual property", text: "AI-generated meal plans are provided for your personal use only. You may not resell or commercially distribute them." },
          ],
        },
        {
          title: "6. User Content",
          items: [
            { subtitle: "Your data", text: "Data you enter (meal logs, health goals, booking notes) remains yours. We use it only to provide the Service as described in our Privacy Policy." },
            { subtitle: "Reviews", text: "By submitting a trainer review, you grant us a non-exclusive license to display it on the platform. Reviews must be honest and not defamatory." },
          ],
        },
        {
          title: "7. Limitation of Liability",
          items: [
            { subtitle: "Service availability", text: "We aim for 99% uptime but do not guarantee uninterrupted access. We are not liable for losses due to service outages." },
            { subtitle: "Health disclaimer", text: "NourishAI is a wellness tool, not a medical device. We are not responsible for any health outcomes resulting from use of our Service. Always seek professional medical advice." },
            { subtitle: "Maximum liability", text: "To the fullest extent permitted by Indian law, our total liability to you shall not exceed the amount you paid us in the 3 months preceding any claim." },
          ],
        },
        {
          title: "8. Termination",
          items: [
            { subtitle: "By you", text: "You may close your account at any time from Account Settings or by emailing support@nourishai.com." },
            { subtitle: "By us", text: "We may suspend or terminate accounts that violate these Terms, with or without notice. Serious violations (fraud, harassment, off-platform payments) result in immediate permanent termination." },
          ],
        },
        {
          title: "9. Governing Law",
          items: [
            { subtitle: "Jurisdiction", text: "These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka." },
            { subtitle: "Dispute resolution", text: "We encourage resolving disputes amicably first. Contact us at support@nourishai.com. If unresolved, disputes shall be settled by arbitration under the Arbitration and Conciliation Act, 1996." },
          ],
        },
      ].map((section, i) => (
        <div key={i} className="card anim-fade-up-3" style={{ marginBottom: 16 }}>
          <h2 style={{ fontFamily: "var(--font-display)", fontSize: 20, color: "var(--primary-dark)", marginBottom: 16 }}>{section.title}</h2>
          {section.items.map((item, j) => (
            <div key={j} style={{ marginBottom: 14, paddingBottom: 14, borderBottom: j < section.items.length - 1 ? "1px solid var(--border)" : "none" }}>
              <div style={{ fontWeight: 600, fontSize: 14, color: "var(--text)", marginBottom: 4 }}>{item.subtitle}</div>
              <p style={{ fontSize: 14, color: "var(--text-3)", lineHeight: 1.7, margin: 0 }}>{item.text}</p>
            </div>
          ))}
        </div>
      ))}

      <div className="card" style={{ textAlign: "center", padding: 32 }}>
        <h3 style={{ fontFamily: "var(--font-display)", fontSize: 18, color: "var(--primary-dark)", marginBottom: 10 }}>Questions about these Terms?</h3>
        <p style={{ fontSize: 14, color: "var(--text-3)", marginBottom: 16 }}>Contact our legal team:</p>
        <a href="mailto:legal@nourishai.com" className="btn btn-primary btn-sm">📧 legal@nourishai.com</a>
        <div style={{ display: "flex", gap: 16, justifyContent: "center", marginTop: 20, flexWrap: "wrap" }}>
          <button onClick={() => navigate("privacy")} style={{ background: "none", border: "none", color: "var(--primary)", cursor: "pointer", fontSize: 14, fontFamily: "var(--font-body)" }}>Privacy Policy</button>
          <button onClick={() => navigate("guidelines")} style={{ background: "none", border: "none", color: "var(--primary)", cursor: "pointer", fontSize: 14, fontFamily: "var(--font-body)" }}>Platform Guidelines</button>
        </div>
      </div>
    </div>
  );
}
