import { useState } from "react";

const API_URL = "https://meal-planner-backend-0ul2.onrender.com/api/meal-plan";

const PLANS = [
  { id: "free", label: "Free", price: "$0", color: "#a3b18a", perks: ["1 meal plan/month", "Basic recipes", "3-day plans only"] },
  { id: "pro", label: "Pro", price: "$9/mo", color: "#588157", perks: ["Unlimited plans", "Full 7-day plans", "Shopping list", "Swap meals"] },
  { id: "family", label: "Family", price: "$19/mo", color: "#3a5a40", perks: ["Everything in Pro", "Up to 6 profiles", "Nutrition analysis", "Pantry tracker"] },
];

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

const defaultPrefs = {
  diet: "No restrictions",
  calories: "2000 kcal",
  cuisine: "Any",
  allergies: "",
  family: "2",
  goal: "Balanced healthy eating",
};

export default function App() {
  const [view, setView] = useState("home"); // home | planner | pricing
  const [prefs, setPrefs] = useState(defaultPrefs);
  const [loading, setLoading] = useState(false);
  const [mealPlan, setMealPlan] = useState(null);
  const [error, setError] = useState("");
  const [activePlan, setActivePlan] = useState("free");
  const [activeDay, setActiveDay] = useState("Monday");
  const [showShoppingList, setShowShoppingList] = useState(false);

  async function generateMealPlan() {
    setLoading(true);
    setError("");
    setMealPlan(null);
    setShowShoppingList(false);

    const isPro = activePlan === "pro" || activePlan === "family";
    const days = isPro ? DAYS : DAYS.slice(0, 3);

    const prompt = `You are a professional nutritionist. Generate a ${days.length}-day meal plan for a family of ${prefs.family}.
Dietary preference: ${prefs.diet}
Daily calorie target: ${prefs.calories}
Cuisine preference: ${prefs.cuisine}
Allergies/Restrictions: ${prefs.allergies || "None"}
Health goal: ${prefs.goal}

Respond ONLY with a valid JSON object. No markdown, no backticks, no explanation. Format:
{
  "days": [
    {
      "day": "Monday",
      "meals": {
        "breakfast": { "name": "...", "calories": 400, "time": "10 min", "description": "..." },
        "lunch": { "name": "...", "calories": 600, "time": "20 min", "description": "..." },
        "dinner": { "name": "...", "calories": 700, "time": "30 min", "description": "..." },
        "snack": { "name": "...", "calories": 200, "time": "5 min", "description": "..." }
      }
    }
  ],
  "shopping_list": {
    "Produce": ["item1", "item2"],
    "Proteins": ["item1"],
    "Dairy": ["item1"],
    "Grains": ["item1"],
    "Pantry": ["item1"]
  },
  "nutrition_summary": "Brief 1-2 sentence summary of the plan's nutritional balance."
}`;

    try {
      const response = await fetch(API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-5",
          max_tokens: 4096,
          messages: [{ role: "user", content: prompt }],
        }),
      });
      const data = await response.json();
      const text = data.content?.map(i => i.text || "").join("") || "";
      const clean = text.replace(/```json|```/g, "").trim();
      const parsed = JSON.parse(clean);
      setMealPlan(parsed);
      setActiveDay(parsed.days[0]?.day || "Monday");
      setView("planner");
    } catch (e) {
      setError("Something went wrong generating your plan. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  const currentDay = mealPlan?.days?.find(d => d.day === activeDay);

  return (
    <div style={styles.root}>
      <style>{css}</style>

      {/* Nav */}
      <nav style={styles.nav}>
        <div style={styles.logo} onClick={() => setView("home")}>🥗 NourishAI</div>
        <div style={styles.navLinks}>
          <button style={styles.navBtn} onClick={() => setView("home")}>Home</button>
          <button style={styles.navBtn} onClick={() => setView("pricing")}>Pricing</button>
          {mealPlan && <button style={styles.navBtn} onClick={() => setView("planner")}>My Plan</button>}
        </div>
        <div style={{ ...styles.planBadge, background: PLANS.find(p => p.id === activePlan)?.color }}>
          {PLANS.find(p => p.id === activePlan)?.label} Plan
        </div>
      </nav>

      {/* HOME */}
      {view === "home" && (
        <div style={styles.page}>
          <div style={styles.hero}>
            <div style={styles.heroTag}>AI-Powered Nutrition</div>
            <h1 style={styles.heroTitle}>Your Personal<br /><span style={styles.heroAccent}>Meal Planner</span></h1>
            <p style={styles.heroSub}>Personalized weekly meal plans, recipes & shopping lists — generated by AI in seconds.</p>
          </div>

          <div style={styles.card}>
            <h2 style={styles.cardTitle}>Build Your Plan</h2>

            <div style={styles.grid2}>
              <div style={styles.field}>
                <label style={styles.label}>Dietary Preference</label>
                <select style={styles.select} value={prefs.diet} onChange={e => setPrefs({ ...prefs, diet: e.target.value })}>
                  {["No restrictions", "Vegetarian", "Vegan", "Pescatarian", "Keto", "Paleo", "Gluten-free"].map(d => (
                    <option key={d}>{d}</option>
                  ))}
                </select>
              </div>
              <div style={styles.field}>
                <label style={styles.label}>Daily Calories</label>
                <select style={styles.select} value={prefs.calories} onChange={e => setPrefs({ ...prefs, calories: e.target.value })}>
                  {["1500", "1800", "2000", "2200", "2500", "3000"].map(c => (
                    <option key={c}>{c} kcal</option>
                  ))}
                </select>
              </div>
              <div style={styles.field}>
                <label style={styles.label}>Cuisine Style</label>
                <select style={styles.select} value={prefs.cuisine} onChange={e => setPrefs({ ...prefs, cuisine: e.target.value })}>
                  {["Any", "Mediterranean", "Asian", "Indian", "Mexican", "American", "Italian"].map(c => (
                    <option key={c}>{c}</option>
                  ))}
                </select>
              </div>
              <div style={styles.field}>
                <label style={styles.label}>Family Size</label>
                <select style={styles.select} value={prefs.family} onChange={e => setPrefs({ ...prefs, family: e.target.value })}>
                  {["1", "2", "3", "4", "5", "6"].map(n => (
                    <option key={n}>{n} {n === "1" ? "person" : "people"}</option>
                  ))}
                </select>
              </div>
            </div>

            <div style={styles.field}>
              <label style={styles.label}>Allergies / Restrictions</label>
              <input style={styles.input} placeholder="e.g. nuts, shellfish, dairy..." value={prefs.allergies}
                onChange={e => setPrefs({ ...prefs, allergies: e.target.value })} />
            </div>

            <div style={styles.field}>
              <label style={styles.label}>Health Goal</label>
              <select style={styles.select} value={prefs.goal} onChange={e => setPrefs({ ...prefs, goal: e.target.value })}>
                {["Balanced healthy eating", "Weight loss", "Muscle gain", "High protein", "Low carb", "Heart healthy", "Family-friendly"].map(g => (
                  <option key={g}>{g}</option>
                ))}
              </select>
            </div>

            {activePlan === "free" && (
              <div style={styles.freeNotice}>
                🔒 Free plan generates 3-day plans. <span style={styles.upgradeLink} onClick={() => setView("pricing")}>Upgrade for full 7-day plans →</span>
              </div>
            )}

            {error && <div style={styles.error}>{error}</div>}

            <button style={styles.generateBtn} onClick={generateMealPlan} disabled={loading} className="genBtn">
              {loading ? <span className="spinner">⟳</span> : "✨ Generate My Meal Plan"}
            </button>
          </div>
        </div>
      )}

      {/* PLANNER */}
      {view === "planner" && mealPlan && (
        <div style={styles.page}>
          <div style={styles.plannerHeader}>
            <div>
              <h2 style={styles.plannerTitle}>Your Weekly Meal Plan</h2>
              <p style={styles.plannerSub}>{mealPlan.nutrition_summary}</p>
            </div>
            <div style={styles.plannerActions}>
              <button style={styles.secondaryBtn} onClick={() => setShowShoppingList(!showShoppingList)}>
                {showShoppingList ? "📅 View Plan" : "🛒 Shopping List"}
              </button>
              <button style={styles.secondaryBtn} onClick={() => setView("home")}>+ New Plan</button>
            </div>
          </div>

          {!showShoppingList ? (
            <>
              <div style={styles.dayTabs}>
                {mealPlan.days.map(d => (
                  <button key={d.day} style={{ ...styles.dayTab, ...(activeDay === d.day ? styles.dayTabActive : {}) }}
                    onClick={() => setActiveDay(d.day)}>
                    {d.day.slice(0, 3)}
                  </button>
                ))}
                {activePlan === "free" && DAYS.slice(3).map(d => (
                  <button key={d} style={styles.dayTabLocked} onClick={() => setView("pricing")}>
                    {d.slice(0, 3)} 🔒
                  </button>
                ))}
              </div>

              {currentDay && (
                <div style={styles.mealsGrid}>
                  {Object.entries(currentDay.meals).map(([type, meal]) => (
                    <div key={type} style={styles.mealCard} className="mealCard">
                      <div style={styles.mealType}>{type.charAt(0).toUpperCase() + type.slice(1)}</div>
                      <div style={styles.mealName}>{meal.name}</div>
                      <p style={styles.mealDesc}>{meal.description}</p>
                      <div style={styles.mealMeta}>
                        <span style={styles.metaTag}>🔥 {meal.calories} kcal</span>
                        <span style={styles.metaTag}>⏱ {meal.time}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </>
          ) : (
            <div style={styles.shoppingCard}>
              <h3 style={styles.shopTitle}>🛒 Shopping List</h3>
              {activePlan === "free" ? (
                <div style={styles.lockedBox}>
                  <div style={styles.lockIcon}>🔒</div>
                  <p style={styles.lockText}>Shopping lists are available on Pro & Family plans.</p>
                  <button style={styles.upgradeBtn} onClick={() => setView("pricing")}>Upgrade Now →</button>
                </div>
              ) : (
                <div style={styles.shopGrid}>
                  {Object.entries(mealPlan.shopping_list).map(([cat, items]) => (
                    <div key={cat} style={styles.shopCategory}>
                      <div style={styles.shopCat}>{cat}</div>
                      {items.map(item => (
                        <div key={item} style={styles.shopItem}>☐ {item}</div>
                      ))}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* PRICING */}
      {view === "pricing" && (
        <div style={styles.page}>
          <div style={styles.hero}>
            <h2 style={styles.heroTitle}>Simple <span style={styles.heroAccent}>Pricing</span></h2>
            <p style={styles.heroSub}>Start free. Upgrade when you're ready.</p>
          </div>
          <div style={styles.pricingGrid}>
            {PLANS.map(plan => (
              <div key={plan.id} style={{ ...styles.pricingCard, ...(activePlan === plan.id ? { border: `2px solid ${plan.color}`, transform: "scale(1.03)" } : {}) }}
                className="pricingCard">
                <div style={{ ...styles.pricingColor, background: plan.color }} />
                <div style={styles.pricingLabel}>{plan.label}</div>
                <div style={styles.pricingPrice}>{plan.price}</div>
                <ul style={styles.perkList}>
                  {plan.perks.map(p => <li key={p} style={styles.perk}>✓ {p}</li>)}
                </ul>
                <button style={{ ...styles.selectPlanBtn, background: plan.color }}
                  onClick={() => { setActivePlan(plan.id); setView("home"); }}>
                  {activePlan === plan.id ? "Current Plan" : "Select Plan"}
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  root: { minHeight: "100vh", background: "#f4f1ec", fontFamily: "'Georgia', serif", color: "#2c2c2c" },
  nav: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 32px", background: "#fff", borderBottom: "1px solid #e8e3da", position: "sticky", top: 0, zIndex: 100 },
  logo: { fontSize: "22px", fontWeight: "bold", color: "#3a5a40", cursor: "pointer", letterSpacing: "-0.5px" },
  navLinks: { display: "flex", gap: "8px" },
  navBtn: { background: "none", border: "none", padding: "8px 16px", cursor: "pointer", fontSize: "14px", color: "#555", borderRadius: "6px", fontFamily: "inherit" },
  planBadge: { padding: "6px 14px", borderRadius: "20px", color: "#fff", fontSize: "12px", fontWeight: "bold", letterSpacing: "0.5px" },
  page: { maxWidth: "900px", margin: "0 auto", padding: "40px 20px" },
  hero: { textAlign: "center", marginBottom: "40px" },
  heroTag: { display: "inline-block", background: "#d8f3dc", color: "#3a5a40", padding: "4px 14px", borderRadius: "20px", fontSize: "13px", marginBottom: "16px", fontFamily: "sans-serif" },
  heroTitle: { fontSize: "clamp(36px, 6vw, 56px)", fontWeight: "bold", lineHeight: 1.15, margin: "0 0 16px", color: "#1a2e1a" },
  heroAccent: { color: "#588157" },
  heroSub: { fontSize: "17px", color: "#666", maxWidth: "480px", margin: "0 auto", fontFamily: "sans-serif", lineHeight: 1.6 },
  card: { background: "#fff", borderRadius: "16px", padding: "36px", boxShadow: "0 4px 24px rgba(0,0,0,0.07)" },
  cardTitle: { fontSize: "22px", fontWeight: "bold", marginBottom: "24px", color: "#1a2e1a" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "16px" },
  field: { marginBottom: "16px" },
  label: { display: "block", fontSize: "13px", fontWeight: "bold", color: "#555", marginBottom: "6px", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: "0.5px" },
  select: { width: "100%", padding: "10px 14px", borderRadius: "8px", border: "1.5px solid #ddd", fontSize: "15px", background: "#fafaf8", fontFamily: "inherit", outline: "none", cursor: "pointer" },
  input: { width: "100%", padding: "10px 14px", borderRadius: "8px", border: "1.5px solid #ddd", fontSize: "15px", background: "#fafaf8", fontFamily: "inherit", outline: "none", boxSizing: "border-box" },
  freeNotice: { background: "#f0f7ee", border: "1px solid #c7e0c8", borderRadius: "8px", padding: "12px 16px", fontSize: "14px", marginBottom: "20px", fontFamily: "sans-serif" },
  upgradeLink: { color: "#3a5a40", cursor: "pointer", fontWeight: "bold", textDecoration: "underline" },
  error: { background: "#fee", border: "1px solid #fcc", borderRadius: "8px", padding: "12px", fontSize: "14px", marginBottom: "16px", fontFamily: "sans-serif", color: "#c00" },
  generateBtn: { width: "100%", padding: "16px", background: "#3a5a40", color: "#fff", border: "none", borderRadius: "10px", fontSize: "17px", fontWeight: "bold", cursor: "pointer", fontFamily: "inherit", marginTop: "8px", letterSpacing: "0.3px" },
  plannerHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "28px", flexWrap: "wrap", gap: "16px" },
  plannerTitle: { fontSize: "28px", fontWeight: "bold", margin: "0 0 6px", color: "#1a2e1a" },
  plannerSub: { fontSize: "14px", color: "#666", margin: 0, fontFamily: "sans-serif", maxWidth: "500px" },
  plannerActions: { display: "flex", gap: "10px" },
  secondaryBtn: { padding: "10px 18px", background: "#fff", border: "1.5px solid #3a5a40", color: "#3a5a40", borderRadius: "8px", fontSize: "14px", cursor: "pointer", fontFamily: "inherit", fontWeight: "bold" },
  dayTabs: { display: "flex", gap: "8px", marginBottom: "24px", flexWrap: "wrap" },
  dayTab: { padding: "8px 18px", borderRadius: "20px", border: "1.5px solid #ddd", background: "#fff", cursor: "pointer", fontSize: "14px", fontFamily: "inherit", color: "#555" },
  dayTabActive: { background: "#3a5a40", color: "#fff", border: "1.5px solid #3a5a40" },
  dayTabLocked: { padding: "8px 18px", borderRadius: "20px", border: "1.5px solid #ddd", background: "#f5f5f5", cursor: "pointer", fontSize: "13px", fontFamily: "inherit", color: "#aaa" },
  mealsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "16px" },
  mealCard: { background: "#fff", borderRadius: "12px", padding: "20px", boxShadow: "0 2px 12px rgba(0,0,0,0.06)", transition: "transform 0.2s" },
  mealType: { fontSize: "11px", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: "1px", color: "#588157", fontWeight: "bold", marginBottom: "8px" },
  mealName: { fontSize: "17px", fontWeight: "bold", marginBottom: "8px", color: "#1a2e1a", lineHeight: 1.3 },
  mealDesc: { fontSize: "13px", color: "#777", fontFamily: "sans-serif", lineHeight: 1.5, margin: "0 0 12px" },
  mealMeta: { display: "flex", gap: "8px", flexWrap: "wrap" },
  metaTag: { background: "#f0f7ee", color: "#3a5a40", padding: "4px 10px", borderRadius: "12px", fontSize: "12px", fontFamily: "sans-serif" },
  shoppingCard: { background: "#fff", borderRadius: "16px", padding: "32px", boxShadow: "0 4px 24px rgba(0,0,0,0.07)" },
  shopTitle: { fontSize: "22px", fontWeight: "bold", marginBottom: "24px", color: "#1a2e1a" },
  lockedBox: { textAlign: "center", padding: "48px 24px" },
  lockIcon: { fontSize: "48px", marginBottom: "16px" },
  lockText: { fontSize: "16px", color: "#666", fontFamily: "sans-serif", marginBottom: "20px" },
  upgradeBtn: { padding: "12px 28px", background: "#3a5a40", color: "#fff", border: "none", borderRadius: "8px", fontSize: "15px", cursor: "pointer", fontFamily: "inherit", fontWeight: "bold" },
  shopGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "20px" },
  shopCategory: {},
  shopCat: { fontSize: "12px", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: "1px", fontWeight: "bold", color: "#588157", marginBottom: "10px" },
  shopItem: { fontSize: "14px", fontFamily: "sans-serif", color: "#444", marginBottom: "6px" },
  pricingGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "24px" },
  pricingCard: { background: "#fff", borderRadius: "16px", padding: "32px", boxShadow: "0 4px 20px rgba(0,0,0,0.07)", border: "2px solid transparent", transition: "all 0.2s", position: "relative", overflow: "hidden" },
  pricingColor: { position: "absolute", top: 0, left: 0, right: 0, height: "5px" },
  pricingLabel: { fontSize: "13px", fontFamily: "sans-serif", textTransform: "uppercase", letterSpacing: "1px", color: "#777", marginBottom: "8px", marginTop: "8px" },
  pricingPrice: { fontSize: "36px", fontWeight: "bold", color: "#1a2e1a", marginBottom: "20px" },
  perkList: { listStyle: "none", padding: 0, margin: "0 0 24px" },
  perk: { fontSize: "14px", fontFamily: "sans-serif", color: "#555", marginBottom: "8px", paddingLeft: "4px" },
  selectPlanBtn: { width: "100%", padding: "12px", color: "#fff", border: "none", borderRadius: "8px", fontSize: "15px", cursor: "pointer", fontFamily: "inherit", fontWeight: "bold" },
};

const css = `
  @keyframes spin { to { transform: rotate(360deg); } }
  .spinner { display: inline-block; animation: spin 0.8s linear infinite; }
  .genBtn:hover:not(:disabled) { background: #2d4a32 !important; transform: translateY(-1px); transition: all 0.2s; }
  .genBtn:disabled { opacity: 0.6; cursor: not-allowed; }
  .mealCard:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(0,0,0,0.1); }
  .pricingCard:hover { transform: translateY(-4px); box-shadow: 0 12px 32px rgba(0,0,0,0.12); }
  @media (max-width: 600px) {
    div[style*="grid-template-columns: 1fr 1fr"] { grid-template-columns: 1fr !important; }
  }
`;